FROM openjdk:11.0.4-jre-slim
VOLUME /tmp
ARG JAR_FILE
COPY ${JAR_FILE} deploymentsmanagementconfigService.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/deploymentsmanagementconfigService.jar"]

#run maven command to build docker image: mvn install dockerfile:build
#run docker file using: docker run --name=deploymentsConfigService -d -p 8182:8182 -it depmgr/deploymentsmanagementconfigservice:latest