FROM amazoncorretto:11.0.4
VOLUME /tmp

RUN mkdir /depExports

ARG JAR_FILE
COPY ${JAR_FILE} sdacontroller.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom", "-jar", "-DmongoDBURL=mongodb://host.docker.internal:27016", "/sdacontroller.jar"]
