FROM openjdk:11.0.4-jre-slim
VOLUME /tmp

RUN mkdir /config
COPY config/security.properties /config/security.properties

ARG JAR_FILE
COPY ${JAR_FILE} deploymentsmanagementcontroller.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom", "-jar", "-DmongoDBURL=mongodb://host.docker.internal:27016", "/deploymentsmanagementcontroller.jar"]
#run docker file using: docker run --name=deploymentsController -d -p 8080:8080 -it --mount src="/c/depExports",dst=/depExports,type=bind depmgr/deploymentsmanagementcontroller:latest